### ISSUE TITLE
Commands for training models on MNIST and KTH

### ISSUE THREAD

**Issue by zzzzzx-1115** [Kay1794/MMVP-motion-matrix-based-video-prediction#5]
Thanks for your awesome work! I notice that you have given an example of how to train MMVP on UCF in README, but I am confused by so many arguments in the command line you have provided. Could you please share commands for MNIST and KTH, which lead to the results you show in your paper?

Thanks for your help!

**Comment by Kay1794** [comment]
Hi,

Thank you very much for your Interest! In the [appendix](https://openaccess.thecvf.com/content/ICCV2023/supplemental/Zhong_MMVP_Motion-Matrix-Based_Video_ICCV_2023_supplemental.pdf), we have included the necessary parameters in Table 2.  For MNIST and KTH, you need to add a flag of **--use_direct_predictor** to make the system be flexible for variable predicted lengths and modify the hyper parameters following Table 2.

For example, according to Table 2 in the Appendix, the command for KTH is:

python main.py --exp EXP_NAME --base_channel 16 **--pred_base_channel 96** --mode train **--dataset kth** --rot_aug --flip_aug --cos_restart --t_period 50 --nepoch 150 --loss_list recon --batch 16 --logpath ./results/ --filter_block --scale_in_use 3 --res_cat_img **--downsample_scale 2 2 2** --lr 1e-3 **--fut_len 20 (or 40)**  **--use_direct_predictor**

Please note that we did not especially tune those parameters for performance, so you may try your own combinations to fit your running environment (GPU memory) or obtain better performances.

**Comment by zzzzzx-1115** [comment]
I am quite grateful that I have successfully run the experiment with the kind help of you.

**Comment by 54wb** [comment]
hi, the base_channel argument wrote in README is 16 for UCF Sports dataset, but the appendix Table 2 show UCF Cimg is 32, so I wondering if Cimg in Table 2 correspond  to this base_channel argument 
Thanks for your help!

**Comment by Kay1794** [comment]
> hi, the base_channel argument wrote in README is 16 for UCF Sports dataset, but the appendix Table 2 show UCF Cimg is 32, so I wondering if Cimg in Table 2 correspond to this base_channel argument
> Thanks for your help!

Yes you are correct. Cimg in Table2 is the base_channel in the command.
